---

resources:
- name: git-resource
  type: git
  source:
    uri: https://github.com/YashMangla/autoartifactory.git
    branch: main
    private_key: ((git-private-key))



jobs:
- name: job-run-update
  plan: 
  - get: git-resource
    trigger: true
  - task: run-update
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs: 
        - name: git-resource
      outputs:
        - name: distribution-repo
      run:
        path: /bin/sh
        args:
        - -c
        - |
          ls /tmp/build/
          pwd
          ls
          ls git-resource
          ls distribution-repo
          cd git-resource
          chmod +x build.sh
          ./build.sh
        
 