---
resources:
- name: git-resource
  type: git
  source:
    uri: https://github.com/YashMangla/autoartifactory.git
    branch: main
    private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACBF37j8nC6NkR2yhOlIQpEtBK6CfDsD6EMcd2FlbGLWnQAAAJi6SREBukkR
      AQAAAAtzc2gtZWQyNTUxOQAAACBF37j8nC6NkR2yhOlIQpEtBK6CfDsD6EMcd2FlbGLWnQ
      AAAEBs8Mom2NoFb+O6py0ohxRQ/kEtKcOBHCqr9hjLbT7I3kXfuPycLo2RHbKE6UhCkS0E
      roJ8OwPoQxx3YWVsYtadAAAAE3ltYW5nbGEzN0BnbWFpbC5jb20BAg==
      -----END OPENSSH PRIVATE KEY-----
  icon: github-circle



jobs:
- name: job-run-update
  plan: 
  - get: git-resource
    trigger: true
  - task: run-update
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: /bin/sh
        args:
        - -c
        - |
          apt-get -y update
          apt-get install git -y
          apt-get install curl -y
          apt-get install iputils-ping -y
          git init
          git clone https://github.com/YashMangla/autoartifactory.git
          cd autoartifactory
          pwd
          ls
          ./update.sh
          


          
