---
resources:
- name: git-resource
  type: git
  source:
    uri: ((git-uri))
    branch: main
    private_key: ((git-private-key))


jobs:
- name: job-run-update
  plan: 
  - get: git-resource
    trigger: true
  - task: run-update
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      input: 
        - name: git-resource
      output:
        - name: distribution-repo
      run:
        path: git-resource/build.sh
        
 